// <auto-generated />
using System;
using BackEncordados.Common.Database.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackEncordados.Migrations.User
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20260526230814_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackEncordados.Usuarios.Model.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<double>("Bonos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("CloudinaryPublicId")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TournamentId")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_users_email_unique");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_users_username_unique");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "01KS0Q28TESE956013XYJKP6ST",
                            Bonos = 0.0,
                            CreatedAt = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@encordados.com",
                            ImageUrl = "avatar-photo-default-user-icon-600nw-2558759027_y1hcma",
                            IsDeleted = false,
                            Name = "Administrador",
                            PasswordHash = "$2a$11$qxEUeoXVUOqGr/HlrrDUZeRsMDcQwoiclUJZOsqEiGI/iCwx1TQDm",
                            Phone = "912345678",
                            Role = "ADMIN",
                            UpdatedAt = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "admin_encordados",
                            Version = 0L
                        },
                        new
                        {
                            Id = "01KS0Q28TE2EFVQTCW8EN0W0MF",
                            Bonos = 0.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "owner@encordados.com",
                            ImageUrl = "avatar-photo-default-user-icon-600nw-2558759027_y1hcma",
                            IsDeleted = false,
                            Name = "Propietario",
                            PasswordHash = "$2a$11$8fZDZSSFPWUG7wP8PKVGpecehuSNofLupnr6o9eG.9rggszddiUEO",
                            Phone = "923456789",
                            Role = "OWNER",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "owner_principal",
                            Version = 0L
                        },
                        new
                        {
                            Id = "01KS0Q28TE7CMWS2D8RVDFA7YJ",
                            Bonos = 0.0,
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carlos@encordados.com",
                            ImageUrl = "avatar-photo-default-user-icon-600nw-2558759027_y1hcma",
                            IsDeleted = false,
                            Name = "Carlos García",
                            PasswordHash = "$2a$11$h4sq7OQFn9BItSjblbZwYe7O.aNbp40eM5A2tXZyLlXhK2WALoI7.",
                            Phone = "934567890",
                            Role = "ENCORDER",
                            UpdatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "carlos_encordador",
                            Version = 0L
                        },
                        new
                        {
                            Id = "01KS0Q28TE6CVB0NYYANTWEK7B",
                            Bonos = 0.0,
                            CreatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maria@encordados.com",
                            ImageUrl = "avatar-photo-default-user-icon-600nw-2558759027_y1hcma",
                            IsDeleted = false,
                            Name = "María López",
                            PasswordHash = "$2a$11$h4sq7OQFn9BItSjblbZwYe7O.aNbp40eM5A2tXZyLlXhK2WALoI7.",
                            Phone = "945678901",
                            Role = "ENCORDER",
                            UpdatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "maria_encordadora",
                            Version = 0L
                        },
                        new
                        {
                            Id = "01KS0Q28TD6SAPN0GN0XKRPK5D",
                            Bonos = 100.0,
                            CreatedAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "juan@tenis.com",
                            ImageUrl = "avatar-photo-default-user-icon-600nw-2558759027_y1hcma",
                            IsDeleted = false,
                            Name = "Juan Martínez",
                            PasswordHash = "$2a$11$vm89IAT3Kz8i95DTqRg6nuXd8EsUIRdgdFhHvezM7TBvMoidExpt.",
                            Phone = "956789012",
                            Role = "USER",
                            TournamentId = "01KS0Q28TEJ0SYA6JJ5H4W4CMP",
                            UpdatedAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "jugador_juan",
                            Version = 0L
                        },
                        new
                        {
                            Id = "01KS0Q28TE3RJTW6W35NJRMTZ4",
                            Bonos = 25.0,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ana@tenis.com",
                            ImageUrl = "avatar-photo-default-user-icon-600nw-2558759027_y1hcma",
                            IsDeleted = false,
                            Name = "Ana Pérez",
                            PasswordHash = "$2a$11$vm89IAT3Kz8i95DTqRg6nuXd8EsUIRdgdFhHvezM7TBvMoidExpt.",
                            Phone = "967890123",
                            Role = "USER",
                            TournamentId = "01KS0Q28TEJ0SYA6JJ5H4W4CMP",
                            UpdatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "jugador_ana",
                            Version = 0L
                        },
                        new
                        {
                            Id = "01KS0Q28TED4PWJPT7DMJ46WBN",
                            Bonos = 0.0,
                            CreatedAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "pedro@tenis.com",
                            ImageUrl = "avatar-photo-default-user-icon-600nw-2558759027_y1hcma",
                            IsDeleted = false,
                            Name = "Pedro Rodríguez",
                            PasswordHash = "$2a$11$vm89IAT3Kz8i95DTqRg6nuXd8EsUIRdgdFhHvezM7TBvMoidExpt.",
                            Phone = "978901234",
                            Role = "USER",
                            TournamentId = "01KS0Q28TE9N7TG55K98TCB4X0",
                            UpdatedAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "jugador_pedro",
                            Version = 0L
                        },
                        new
                        {
                            Id = "01KS0Q28TEHA2KF5YM3J6QS5Z9",
                            Bonos = 0.0,
                            CreatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "luis@encordados.com",
                            ImageUrl = "avatar-photo-default-user-icon-600nw-2558759027_y1hcma",
                            IsDeleted = false,
                            Name = "Luis Fernández",
                            PasswordHash = "$2a$11$xl2gKmt6XzEkFpdjbHVpEOHw2sbCo2kFZZhVG38lqst9PxxmR1Dda",
                            Phone = "989012345",
                            Role = "SUPERVISOR",
                            UpdatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "supervisor_luis",
                            Version = 0L
                        },
                        new
                        {
                            Id = "01KS0Q28TEXTDY9TQNRAXKAJ81",
                            Bonos = 0.0,
                            CreatedAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "pablo@encordados.com",
                            ImageUrl = "avatar-photo-default-user-icon-600nw-2558759027_y1hcma",
                            IsDeleted = false,
                            Name = "Pablo Sánchez",
                            PasswordHash = "$2a$11$xl2gKmt6XzEkFpdjbHVpEOHw2sbCo2kFZZhVG38lqst9PxxmR1Dda",
                            Phone = "990123456",
                            Role = "SUPERVISOR",
                            UpdatedAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "supervisor_pablo",
                            Version = 0L
                        },
                        new
                        {
                            Id = "01KS0Q28TE5BA449NS2EVCBTDQ",
                            Bonos = 0.0,
                            CreatedAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user@example.com",
                            ImageUrl = "avatar-photo-default-user-icon-600nw-2558759027_y1hcma",
                            IsDeleted = false,
                            Name = "User",
                            PasswordHash = "$2a$11$vm89IAT3Kz8i95DTqRg6nuXd8EsUIRdgdFhHvezM7TBvMoidExpt.",
                            Phone = "999999000",
                            Role = "USER",
                            UpdatedAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "user",
                            Version = 0L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
