name: local
variables:
  - name: api-url
    value: http://localhost:5032
  - name: token
    value: ""
  - name: token_owner
    value: ""
  - name: token_encoder
    value: ""
  - name: token_supervisor
    value: ""
  - name: supervisor_id_luis
    value: "01KR424NQJKTASKDL3M5NP7GHS"
  - name: supervisor_id_pablo
    value: "01KR424NQJKUBMAEM4N6OQ8JIT"
