// <auto-generated />
using System;
using BackEncordados.Common.Database.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackEncordados.Migrations.Materials
{
    [DbContext(typeof(MaterialsDbContext))]
    [Migration("20260528234737_DropUniqueIndexesMaterialsAndCuerdas")]
    partial class DropUniqueIndexesMaterialsAndCuerdas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackEncordados.Materials.Model.Cuerdas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Calibre")
                        .HasColumnType("double precision");

                    b.Property<string>("CloudinaryPublicId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Precio")
                        .HasColumnType("double precision");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<string>("StringFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StringsType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TournamentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("Cuerdas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Calibre = 1.25,
                            CreatedAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-680x600_kw5ji6",
                            IsDeleted = false,
                            Marca = "Babolat",
                            Modelo = "RPM Blast",
                            Precio = 19.989999999999998,
                            Stock = 50,
                            StringFormat = "Reel",
                            StringsType = "Polyester",
                            TournamentId = "01KS0Q28TEJ0SYA6JJ5H4W4CMP",
                            UpdatedAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2L,
                            Calibre = 1.3,
                            CreatedAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-680x600_kw5ji6",
                            IsDeleted = false,
                            Marca = "Wilson",
                            Modelo = "Champion's Choice",
                            Precio = 24.989999999999998,
                            Stock = 20,
                            StringFormat = "Set",
                            StringsType = "NaturalGut",
                            TournamentId = "01KS0Q28TEJ0SYA6JJ5H4W4CMP",
                            UpdatedAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3L,
                            Calibre = 1.25,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-680x600_kw5ji6",
                            IsDeleted = false,
                            Marca = "Luxilon",
                            Modelo = "ALU Power",
                            Precio = 21.989999999999998,
                            Stock = 45,
                            StringFormat = "Reel",
                            StringsType = "Polyester",
                            TournamentId = "01KS0Q28TE9N7TG55K98TCB4X0",
                            UpdatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4L,
                            Calibre = 1.3,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-680x600_kw5ji6",
                            IsDeleted = false,
                            Marca = "Head",
                            Modelo = "Intellitour",
                            Precio = 18.5,
                            Stock = 30,
                            StringFormat = "Set",
                            StringsType = "Multifilament",
                            TournamentId = "01KS0Q28TE9N7TG55K98TCB4X0",
                            UpdatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5L,
                            Calibre = 1.28,
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-680x600_kw5ji6",
                            IsDeleted = false,
                            Marca = "Signum Pro",
                            Modelo = "Plasma",
                            Precio = 17.989999999999998,
                            Stock = 25,
                            StringFormat = "Reel",
                            StringsType = "Hybrid",
                            TournamentId = "01KS0Q28TEVEYS4303TXP202N4",
                            UpdatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6L,
                            Calibre = 1.25,
                            CreatedAt = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-680x600_kw5ji6",
                            IsDeleted = false,
                            Marca = "Kirschbaum",
                            Modelo = "Pro Line",
                            Precio = 15.99,
                            Stock = 35,
                            StringFormat = "Set",
                            StringsType = "SyntheticGut",
                            TournamentId = "01KS0Q28TET0JHJV4T5YFDJWBW",
                            UpdatedAt = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7L,
                            Calibre = 1.3,
                            CreatedAt = new DateTime(2025, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-680x600_kw5ji6",
                            IsDeleted = false,
                            Marca = "Babolat",
                            Modelo = "VS Team",
                            Precio = 22.0,
                            Stock = 40,
                            StringFormat = "Reel",
                            StringsType = "NaturalGut",
                            TournamentId = "01KS0Q28TE5BA449NS2EVCBTDQ",
                            UpdatedAt = new DateTime(2025, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8L,
                            Calibre = 1.3,
                            CreatedAt = new DateTime(2025, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-680x600_kw5ji6",
                            IsDeleted = false,
                            Marca = "Technifibre",
                            Modelo = "XR2",
                            Precio = 18.5,
                            Stock = 60,
                            StringFormat = "Set",
                            StringsType = "Polyester",
                            TournamentId = "01KS0Q28TE5BA449NS2EVCBTDQ",
                            UpdatedAt = new DateTime(2025, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BackEncordados.Materials.Model.Material", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CloudinaryPublicId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Precio")
                        .HasColumnType("double precision");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<string>("TournamentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("Materiales", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-680x600_kw5ji6",
                            IsDeleted = false,
                            Marca = "Head",
                            Modelo = "Hydrosorb Comfort",
                            Precio = 8.9900000000000002,
                            Stock = 100,
                            TournamentId = "01KS0Q28TEJ0SYA6JJ5H4W4CMP",
                            Type = "Grip",
                            UpdatedAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-680x600_kw5ji6",
                            IsDeleted = false,
                            Marca = "Babolat",
                            Modelo = "Pro Overgrip",
                            Precio = 3.9900000000000002,
                            Stock = 200,
                            TournamentId = "01KS0Q28TEJ0SYA6JJ5H4W4CMP",
                            Type = "Overgrip",
                            UpdatedAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-680x600_kw5ji6",
                            IsDeleted = false,
                            Marca = "Tourna",
                            Modelo = "Lead Tape 1/2\"",
                            Precio = 12.99,
                            Stock = 80,
                            TournamentId = "01KS0Q28TE9N7TG55K98TCB4X0",
                            Type = "LeadTape",
                            UpdatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-680x600_kw5ji6",
                            IsDeleted = false,
                            Marca = "Wilson",
                            Modelo = "ShockShield",
                            Precio = 9.9900000000000002,
                            Stock = 50,
                            TournamentId = "01KS0Q28TE9N7TG55K98TCB4X0",
                            Type = "Silicone",
                            UpdatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-680x600_kw5ji6",
                            IsDeleted = false,
                            Marca = "Head",
                            Modelo = "Graphene 360+",
                            Precio = 199.99000000000001,
                            Stock = 10,
                            TournamentId = "01KS0Q28TEVEYS4303TXP202N4",
                            Type = "Otro",
                            UpdatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-680x600_kw5ji6",
                            IsDeleted = false,
                            Marca = "Babolat",
                            Modelo = "Syn Pro",
                            Precio = 6.9900000000000002,
                            Stock = 75,
                            TournamentId = "01KS0Q28TET0JHJV4T5YFDJWBW",
                            Type = "Grip",
                            UpdatedAt = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2025, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-680x600_kw5ji6",
                            IsDeleted = false,
                            Marca = "Head",
                            Modelo = "Super Soft",
                            Precio = 7.5,
                            Stock = 150,
                            TournamentId = "01KS0Q28TE5BA449NS2EVCBTDQ",
                            Type = "Grip",
                            UpdatedAt = new DateTime(2025, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2025, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "default-680x600_kw5ji6",
                            IsDeleted = false,
                            Marca = "Tourna",
                            Modelo = "Grip Boost",
                            Precio = 4.9900000000000002,
                            Stock = 100,
                            TournamentId = "01KS0Q28TE5BA449NS2EVCBTDQ",
                            Type = "Overgrip",
                            UpdatedAt = new DateTime(2025, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}

