name: Trigger Parent Build

on:
  push:
    branches:
      - main
      - dev   

jobs:
  notify-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Event to docker-enviroment
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.PARENT_REPO_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Aragorn7372/docker-enviroment/dispatches \
          -d '{"event_type":"submodule_updated","client_payload":{"submodule":"${{ github.event.repository.name }}","branch":"${{ github.ref_name }}"}}'